添加平滑滚动
LittleSkinChina/manual pull request #15
Opened 2020-05-23 12:03 UTC by Cheny233

2020-05-23 12:09 UTC, g-plane requested changes
这 JS 有语法错误，把逗号补上吧。

2020-05-23 12:13 UTC, SerinaNya approved these changes

2020-05-23 12:13 UTC, jinzhijie commented on .vuepress/config.js
> +        smoothscroll: true
``` js
        },
        smoothscroll: true
```

2020-05-23 12:13 UTC, Cheny233 commented
已修改

2020-05-23 12:28 UTC, SerinaNya approved these changes

2020-05-23 13:45 UTC, xfl03 approved these changes

2020-05-23 13:47 UTC, xfl03 commented
@jinzhijie 在代码尚有问题时，请选择“Request changes”而不是“Approve”。

2020-05-23 13:49 UTC, g-plane approved these changes

2020-05-24 01:19 UTC, jinzhijie commented
> @jinzhijie 在代码尚有问题时，请选择“Request changes”而不是“Approve”。

~~其实是我选错了~~

2020-05-24 05:22 UTC, merged

2020-05-24 05:23 UTC, tnqzh123 approved these changes