Update 收不到验证邮件
LittleSkinChina/manual pull request #31
Opened 2020-09-04 14:12 UTC by jinzhijie

加入了更换邮件服务提供商的建议，并提示用户在报告问题时附上自己的邮箱

2020-09-24 09:00 UTC, jinzhijie commented
![image](https://user-images.githubusercontent.com/34389622/94124204-4d59eb00-fe87-11ea-874d-2c9c14ca74b4.png)

此为预览图，请 @tnqzh123 尽快 review

2020-09-28 19:19 UTC, tnqzh123 requested changes

2020-09-28 19:19 UTC, tnqzh123 commented on faq.md
> +<span style="color: red;">请先尝试按下 <kbd>Ctrl</kbd><kbd>F5</kbd> 使浏览器硬性重新加载</span>，如果问题仍然存在，则说明你的浏览器过时了。
Ctrl + F5

没有必要标红

2020-09-29 10:56 UTC, jinzhijie commented
你是指这一整段文字不要标红，还是说仅仅是 ctrl f5 这个 <kbd&gt;？------------------&nbsp;Original&nbsp;------------------
From:&nbsp;&quot;Steven&amp;nbsp;Qiu&quot;<notifications@github.com&gt;
Date:&nbsp;Tue, Sep 29, 2020 03:19 AM
To:&nbsp;&quot;LittleSkinChina/manual&quot;<manual@noreply.github.com&gt;;
Cc:&nbsp;&quot;Xiao_Jin&quot;<742905606@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
Subject:&nbsp;Re: [LittleSkinChina/manual] Update 收不到验证邮件 &amp; 无法正常显示某些页面 / 图片 (#31)

2020-10-01 18:29 UTC, tnqzh123 commented
整段。

2021-07-30 12:13 UTC, tnqzh123 commented on faq.md
> +如果以上两种方法皆不奏效，则很有可能是你的邮件提供商屏蔽了我们发出的验证邮件，请尝试更换邮件服务提供商，并重新发送验证邮件。
“邮件提供商”听起来像是提供邮件发送服务的

直接写“更换邮箱”会不会更好？

2021-07-30 12:13 UTC, tnqzh123 commented on faq.md
> +请先尝试按下 <kbd>Ctrl</kbd><kbd>F5</kbd> 使浏览器硬性重新加载，如果问题仍然存在，则说明你的浏览器过时了。
没必要写“硬性重新加载”，用户不一定看得懂，要不改成“刷新页面并更新本地缓存”？

2021-07-30 12:13 UTC, tnqzh123 commented on faq.md
> +需要特别注意的是，很多中国国内发行的浏览器即使更新到最新版本，其使用的浏览器内核仍然是过时的。我们建议各位使用最新版本的 [Google Chrome](https://www.google.com/chrome) 或 [Mozilla Firefox](https://www.mozilla.org/firefox/new) 或基于 Chromium 内核的 [Microsoft Edge](
前面已经写了“基于 Chromium 内核的”了，没必要再单独标注

2021-07-30 12:14 UTC, closed without merging

2021-07-30 12:22 UTC, jinzhijie commented on faq.md
> +请先尝试按下 <kbd>Ctrl</kbd><kbd>F5</kbd> 使浏览器硬性重新加载，如果问题仍然存在，则说明你的浏览器过时了。
Chrome 里就是这样写的，所以并不想更改

2021-07-30 12:22 UTC, jinzhijie commented on faq.md
> +需要特别注意的是，很多中国国内发行的浏览器即使更新到最新版本，其使用的浏览器内核仍然是过时的。我们建议各位使用最新版本的 [Google Chrome](https://www.google.com/chrome) 或 [Mozilla Firefox](https://www.mozilla.org/firefox/new) 或基于 Chromium 内核的 [Microsoft Edge](
fix in #36