Update faq and newbee
LittleSkinChina/manual pull request #36
Opened 2021-07-30 10:47 UTC by jinzhijie

增加：CustomSkinLoader.json 示例文件以供直接下载
增加：我该使用哪个域名？
增加：无法绑定正版账号？
修改：一些小细节

注：由于新版 CSL 的特性，修改了 json 中的站点名称

将在稍后合并 #33 的建议

2021-07-30 12:21 UTC, tnqzh123 requested changes

2021-07-30 12:21 UTC, tnqzh123 commented on faq.md
> +- `littlesk.in`：托管于 Vercel，根据请求 IP 的地理位置将请求重定向至以上两个域名之一。
这里不用标明具体服务商

2021-07-30 12:21 UTC, tnqzh123 commented on faq.md
> +- `littleskin.cn`：使用 Cloudflare CDN，加速区域为全球，对非中国大陆用户友好；
Cloudflare 免费版没有中国大陆节点

2021-07-30 12:21 UTC, tnqzh123 commented on faq.md
> +在此用户手册中，会多次出现域名相关的内容，请根据以上的介绍，选择合适的域名。如果你使用的域名不合适，则可能导致资源加载失败，速度缓慢等情况。
建议最后一个逗号改顿号，表示并列关系

2021-07-30 12:21 UTC, tnqzh123 commented on faq.md
> +截至目前，正版验证插件暂不支持 Microsoft 账号，但我们会在将来逐步支持。
别写插件了，正版验证功能就行，懂得都懂

2021-07-30 12:21 UTC, tnqzh123 commented on faq.md
> +大多数情况下，这是由你的浏览器导致的，除非你使用了错误的域名或发生了其他问题。关于域名问题，请查看 [我该使用哪个域名？](#我该使用哪个域名)
语序感觉怪怪的，先写域名问题再说浏览器问题吧

2021-07-30 12:21 UTC, tnqzh123 commented on newbee/mod.md
> +CustomSkinLoader 14.4 起支持通过 ExtraList 的方式添加皮肤站，这也是我们推荐的方法之一。你可以在用户中心的「配置生成」页面下载到 LittleSkin 的 ExtraList 文件，将其放入 `.minecraft/CustomSkinLoader/ExtraList/` 目录下即可。
这个是我们定制 BS 的问题，本来这个地方也应该是“皮肤 Mod”，有空修

2021-07-30 12:23 UTC, jinzhijie commented on faq.md
> +- `littleskin.cn`：使用 Cloudflare CDN，加速区域为全球，对非中国大陆用户友好；
中国大陆以外地区，可？

2021-07-30 12:24 UTC, jinzhijie commented on newbee/mod.md
> +CustomSkinLoader 14.4 起支持通过 ExtraList 的方式添加皮肤站，这也是我们推荐的方法之一。你可以在用户中心的「配置生成」页面下载到 LittleSkin 的 ExtraList 文件，将其放入 `.minecraft/CustomSkinLoader/ExtraList/` 目录下即可。
那我应该咋改

2021-07-30 12:25 UTC, jinzhijie commented on faq.md
> +大多数情况下，这是由你的浏览器导致的，除非你使用了错误的域名或发生了其他问题。关于域名问题，请查看 [我该使用哪个域名？](#我该使用哪个域名)
👌，其实我一开始就是先写域名的，后来又被我改了 😐

2021-08-14 22:35 UTC, tnqzh123 requested changes

2021-08-14 22:35 UTC, tnqzh123 commented on faq.md
> +---
为什么这里要加分隔线？好像没必要吧，目录下面自动生成的空白足够分割了

2021-08-14 22:35 UTC, tnqzh123 commented on faq.md
> +请确保您在 LittleSkin 使用的邮箱与您的正版账号的邮箱一致，如不一致，请至个人资料页面更改你的邮箱。
您和你不要混用

2021-08-15 04:21 UTC, jinzhijie commented
@tnqzh123

2021-08-15 04:48 UTC, g-plane commented
请善用 GitHub：

![图片](https://user-images.githubusercontent.com/17216317/129467469-60765947-da77-4201-ad1f-764a1bdfff52.png)

2021-08-15 04:50 UTC, jinzhijie commented
> 请善用 GitHub：
> 
> ![图片](https://user-images.githubusercontent.com/17216317/129467469-60765947-da77-4201-ad1f-764a1bdfff52.png)
> 

sry, 我用的 GitHub Android

2021-08-15 10:33 UTC, tnqzh123 approved these changes

2021-08-15 10:33 UTC, merged