对Microsoft正版验证问题进行补充(#51)
LittleSkinChina/manual pull request #52
Opened 2022-07-30 15:43 UTC by yangnuozhen

详见#51 Microsoft账户正版验证帮助补充

2022-07-31 00:04 UTC, gxres042 approved these changes
初看一眼没问题，等 Owner review

2022-08-01 21:21 UTC, tnqzh123 commented
能不能解释一下？我没看明白，为什么需要用代理？

2022-08-11 06:49 UTC, yangnuozhen commented
> 能不能解释一下？我没看明白，为什么需要用代理？

微软服务器在国外 国内有时候不稳定所以不行就试试代理啦

2022-08-11 06:52 UTC, yangnuozhen commented
> 初看一眼没问题，等 Owner review

好的 谢谢啦(=^▽^=)

2022-08-11 06:53 UTC, jinzhijie commented
> > 能不能解释一下？我没看明白，为什么需要用代理？
> 
> 微软服务器在国外 国内有时候不稳定所以不行就试试代理啦

这也跟代理没有关系呀，微软的服务器又没有被阻断，不需要使用代理。至于你说的不稳定，理论上来说不会存在不稳定这种问题，只是可能慢一点而已。

2022-08-11 06:57 UTC, Nofated095 commented
> > > 能不能解释一下？我没看明白，为什么需要用代理？
> > 
> > 
> > 微软服务器在国外 国内有时候不稳定所以不行就试试代理啦
> 
> 这也跟代理没有关系呀，微软的服务器又没有被阻断，不需要使用代理。至于你说的不稳定，理论上来说不会存在不稳定这种问题，只是可能慢一点而已。

Agree with that.

目前国内访问 live.com 等微软的验证服务器速度还可以
不会出现完全无法访问，被屏蔽，所以我认为没有太大必要提代理（？

2022-08-12 02:18 UTC, Kasugano-h commented
> > > > 能不能解释一下？我没看明白，为什么需要用代理？
> > > 
> > > 
> > > 微软服务器在国外 国内有时候不稳定所以不行就试试代理啦
> > 
> > 
> > 这也跟代理没有关系呀，微软的服务器又没有被阻断，不需要使用代理。至于你说的不稳定，理论上来说不会存在不稳定这种问题，只是可能慢一点而已。
> 
> Agree with that.
> 
> 目前国内访问 live.com 等微软的验证服务器速度还可以 不会出现完全无法访问，被屏蔽，所以我认为没有太大必要提代理（？

在我这里，GFW 已经污染了 `onedirve.live.com`（连接被重置）

而且在西北某地（你明白我指的是哪里），`*.live.com` 均无法连接。

所以我认为提醒使用代理还是很有必要的。

2022-08-12 09:04 UTC, Nofated095 commented
> > > > > 能不能解释一下？我没看明白，为什么需要用代理？
> > > > 
> > > > 
> > > > 微软服务器在国外 国内有时候不稳定所以不行就试试代理啦
> > > 
> > > 
> > > 这也跟代理没有关系呀，微软的服务器又没有被阻断，不需要使用代理。至于你说的不稳定，理论上来说不会存在不稳定这种问题，只是可能慢一点而已。
> > 
> > 
> > Agree with that.
> > 目前国内访问 live.com 等微软的验证服务器速度还可以 不会出现完全无法访问，被屏蔽，所以我认为没有太大必要提代理（？
> 
> 在我这里，GFW 已经污染了 `onedirve.live.com`（`连接被重置`或`连接超时`）
> 
> 而 `*.live.com` 提供的其它服务时好时坏（`连接超时`）
> 
> 而且在西北某地（你明白我指的是哪里），`*.live.com` 均无法连接（`连接被重置`或`连接超时`）
> 
> 所以我认为提醒使用代理还是很有必要的。

我不认为在使用正版验证的时候需要用到 Microsoft Onedrive 的相关域名

但对于西北地区，我认为有道理

2022-08-17 14:49 UTC, yangnuozhen commented
> > > > > > 能不能解释一下？我没看明白，为什么需要用代理？
> > > > > 
> > > > > 
> > > > > 微软服务器在国外 国内有时候不稳定所以不行就试试代理啦
> > > > 
> > > > 
> > > > 这也跟代理没有关系呀，微软的服务器又没有被阻断，不需要使用代理。至于你说的不稳定，理论上来说不会存在不稳定这种问题，只是可能慢一点而已。
> > > 
> > > 
> > > Agree with that.
> > > 目前国内访问 live.com 等微软的验证服务器速度还可以 不会出现完全无法访问，被屏蔽，所以我认为没有太大必要提代理（？
> > 
> > 
> > 在我这里，GFW 已经污染了 `onedirve.live.com`（`连接被重置`或`连接超时`）
> > 而 `*.live.com` 提供的其它服务时好时坏（`连接超时`）
> > 而且在西北某地（你明白我指的是哪里），`*.live.com` 均无法连接（`连接被重置`或`连接超时`）
> > 所以我认为提醒使用代理还是很有必要的。
> 
> 我不认为在使用正版验证的时候需要用到 Microsoft Onedrive 的相关域名
> 
> 但对于西北地区，我认为有道理

我在东南这边 有时候登录Microsoft(XBox)账号有时候会加载不出来、卡在手机号验证这里，我一般是切换网络环境，有时候实在不行才挂代理。（另外挂代理有时候也不是很稳定）

还有这个pr的重点不是挂不挂代理，而是在Microsoft账户验证加入后页面没有及时更新才发起的这个PR(

2022-08-18 01:21 UTC, Restent commented
广西这边确实有裸连不上微软服务器的问题
虽然可以通过改 DNS / HOSTS 解决这个问题，但大多数人应该不会这样做，然后连不上就跑来问三问四的
这个看看后面怎么补充吧，反正我是没搞懂

2022-08-19 04:06 UTC, Kasugano-h commented
等 Owner Review 吧……

2022-08-19 04:33 UTC, yangnuozhen commented
> 广西这边确实有裸连不上微软服务器的问题
> 虽然可以通过改 DNS / HOSTS 解决这个问题，但大多数人应该不会这样做，然后连不上就跑来问三问四的
> 这个看看后面怎么补充吧，反正我是没搞懂

主要还是看owner怎么补充吧 我的建议是用代理 因为我经常会卡住就直接挂代理。

2022-08-19 04:47 UTC, dz-paji commented
这句话的意思是，如果我的密码不正确我要开代理？

2022-08-19 04:47 UTC, dz-paji commented
这句话的意思是，如果我的密码不正确我要开代理？

2022-08-19 04:52 UTC, yangnuozhen commented
> 这句话的意思是，如果我的密码不正确我要开代理？

不是 有时候会出现卡在账户二次验证这边 有时要等很久甚至连接不上你可以试试开代理。

2022-08-19 04:55 UTC, dz-paji commented
> 不是 有时候会出现卡在账户二次验证这边 有时要等很久甚至连接不上你可以试试开代理。

我不认为你写的文档有体现出来这个意思

2022-08-19 04:56 UTC, yangnuozhen commented
可能确实是我的表达有问题。

应该是：
```
请确保你的账户与密码正确且已通过二次验证。

如果出现连接被重置或连接超时（例如卡在二次验证步骤）可以尝试修改HOST或使用代理。
```

2022-08-19 05:53 UTC, chengnan049 commented
> > > > > 能不能解释一下？我没看明白，为什么需要用代理？
> > > > 
> > > > 
> > > > 微软服务器在国外 国内有时候不稳定所以不行就试试代理啦
> > > 
> > > 
> > > 这也跟代理没有关系呀，微软的服务器又没有被阻断，不需要使用代理。至于你说的不稳定，理论上来说不会存在不稳定这种问题，只是可能慢一点而已。
> > 
> > Agree with that.
> > 
> > 目前国内访问 live.com 等微软的验证服务器速度还可以 不会出现完全无法访问，被屏蔽，所以我认为没有太大必要提代理（？
> 
> 在我这里，GFW 已经污染了 `onedirve.live.com`（`连接被重置`或`连接超时`）
> 
> 而 `*.live.com` 提供的其它服务时好时坏（`连接超时`）
> 
> 而且在西北某地（你明白我指的是哪里），`*.live.com` 均无法连接（`连接被重置`或`连接超时`）
> 
> 所以我认为提醒使用代理还是很有必要的。

域名似乎是 `onedrive.live.com`

2022-08-19 08:25 UTC, Kasugano-h commented
> > > > > > 能不能解释一下？我没看明白，为什么需要用代理？
> > > > > 
> > > > > 
> > > > > 微软服务器在国外 国内有时候不稳定所以不行就试试代理啦
> > > > 
> > > > 
> > > > 这也跟代理没有关系呀，微软的服务器又没有被阻断，不需要使用代理。至于你说的不稳定，理论上来说不会存在不稳定这种问题，只是可能慢一点而已。
> > > 
> > > 
> > > Agree with that.
> > > 目前国内访问 live.com 等微软的验证服务器速度还可以 不会出现完全无法访问，被屏蔽，所以我认为没有太大必要提代理（？
> > 
> > 
> > 在我这里，GFW 已经污染了 `onedirve.live.com`（`连接被重置`或`连接超时`）
> > 而 `*.live.com` 提供的其它服务时好时坏（`连接超时`）
> > 而且在西北某地（你明白我指的是哪里），`*.live.com` 均无法连接（`连接被重置`或`连接超时`）
> > 所以我认为提醒使用代理还是很有必要的。
> 
> 域名似乎是 `onedrive.live.com`

打太快手滑了，丢人现场（

2022-08-19 10:58 UTC, Nofated095 commented
我撤回我的观点，我认为在文档中进行提示通过代理链接微软验证服务是不需要的。

2022-08-20 15:29 UTC, yangnuozhen commented
> 我撤回我的观点，我认为在文档中进行提示通过代理链接微软验证服务是不需要的。

可是这是faq，我认为在FAQ文档中应该提到用户可能遇到的问题以及用户可以采取的解决方案。
不过提到代理会不会引起CCP关注我觉得可能是个话题(?

2022-08-20 15:50 UTC, tnqzh123 commented
我说停停。

有些事情点到为止就可以了，不要说太多，即使是在监管不那么严格的环境下也请谨言慎行。

2022-08-20 16:03 UTC, tnqzh123 requested changes
@yangnuozhen 

> 可是这是faq，我认为在FAQ文档中应该提到用户可能遇到的问题以及用户可以采取的解决方案。

这是产品的 FAQ，不是妙招姐的妙招小视频，不是什么东西都适合写进去的。而且考虑到合规性，你提交的内容也确实不太方便写进去。我觉得笼统地写一句「微软服务器在中国大陆地区的连接质量较差，验证时可能遇到网络问题」就差不多了。

而且我还是不理解你的这个“否则”的意思…如果我账号和密码都输入正确了就不需要使用代理？还是说我只要通过代理访问就不需要输入正确的账号和密码？

2022-08-21 11:44 UTC, yangnuozhen commented
> @yangnuozhen
> 
> > 可是这是faq，我认为在FAQ文档中应该提到用户可能遇到的问题以及用户可以采取的解决方案。
> 
> 这是产品的 FAQ，不是妙招姐的妙招小视频，不是什么东西都适合写进去的。而且考虑到合规性，你提交的内容也确实不太方便写进去。我觉得笼统地写一句「微软服务器在中国大陆地区的连接质量较差，验证时可能遇到网络问题」就差不多了。
> 
> 而且我还是不理解你的这个“否则”的意思…如果我账号和密码都输入正确了就不需要使用代理？还是说我只要通过代理访问就不需要输入正确的账号和密码？

确实是我表达有问题 写的时候没太注意(https://github.com/LittleSkinChina/manual/pull/52#issuecomment-1220249635)

2022-08-21 11:46 UTC, yangnuozhen commented
> 而且我还是不理解你的这个“否则”的意思…如果我账号和密码都输入正确了就不需要使用代理？还是说我只要通过代理访问就不需

那么就按照您说的改，在后面追加一个Tip`微软服务器在中国大陆地区的连接质量较差，验证时可能遇到网络问题`

2022-08-22 08:49 UTC, Restent reviewed
我的建议是贴近 VuePress 的语法（使用 ::: tip :::）

2022-08-22 08:58 UTC, Restent commented
> 我的建议是贴近 VuePress 的语法（使用 ::: tip :::）

再加一点。
微软服务器不是所有大陆地区都跟少部分地区一样慢。
有些人能秒速加载出登录页面，有些人不行，以一概全的话我感觉不是很好。

2022-08-22 09:35 UTC, Nofated095 commented on faq.md
> +>Tip:微软服务器在中国大陆地区的连接质量较差，验证时可能遇到网络问题，您可以等待一段时间再重新尝试或者切换一下网络环境。
```suggestion
>:::tip 微软服务器在中国大陆地区的连接质量较差，验证时可能遇到网络问题，您可以等待一段时间再重新尝试或者切换一下网络环境。 :::
```

2022-08-23 13:16 UTC, yangnuozhen commented
> > 我的建议是贴近 VuePress 的语法（使用 ::: tip :::）
> 
> 再加一点。
> 微软服务器不是所有大陆地区都跟少部分地区一样慢。
> 有些人能秒速加载出登录页面，有些人不行，以一概全的话我感觉不是很好。

所以是**可能**出现连接问题啊😂

2022-08-23 13:31 UTC, Nofated095 commented
> > 微软服务器不是所有大陆地区都跟少部分地区一样慢。
> > 有些人能秒速加载出登录页面，有些人不行，以一概全的话我感觉不是很好。
> 
> 所以是**可能**出现连接问题啊😂

现在其实看上去改得我认为比较合适了（）

2022-08-23 13:32 UTC, Nofated095 approved these changes

2022-08-28 17:25 UTC, tnqzh123 approved these changes

2022-09-23 02:34 UTC, Restent commented on faq.md
> +>::: tip 微软服务器在中国大陆地区的连接质量较差，验证时可能遇到网络问题，您可以等待一段时间再重新尝试或者切换一下网络环境。 :::
Suggest Changes:
::: tip
微软服务器在中国大陆地区的连接质量较差，验证时可能遇到网络问题，您可以等待一段时间再重新尝试或者切换一下网络环境。
:::

2022-09-23 02:36 UTC, Restent reviewed
::: tip ::: 和 > 不建议混用，虽然不知道能不能共用

2022-10-04 13:53 UTC, yangnuozhen commented
> ::: tip ::: 和 > 不建议混用，虽然不知道能不能共用

已修改

2023-06-19 17:39 UTC, tnqzh123 approved these changes

2023-06-19 17:40 UTC, merged